config/routes.rb
Rails.application.routes.draw do
  resources :bookings do
    collection do
      get :search
      get :new_reservation

    end
  end
  resources :rooms do
    collection do
      get :search
      get :view_reservation
    end
  end

  resources :users do
    collection do
      post :login
      get :new_user
      get :logout
      get :search
      get :view_reservation
    end
  end

  root 'users#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
 # def user_history
 #   @bookings = Booking.find_by_id(params[:roomno])
  #  @user = @user.courses.sort_by &:id
   # @course_mappings = @user.course_mappings.sort_by &:course_id
    #return @courses, @course_mappings, @user
  #end
  validates :roomno, :booked_user, :starttime,  presence: true
  belongs_to :room
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def search
    search_room = params[:room].reject {|key, value| value.empty? }
    if search_room.values.empty?
      sql_query = "select * from rooms"
      @rooms = Room.find_by_sql(sql_query)
      @bookings = Booking.all
      return @rooms,@bookings
      #redirect_to '/bookings'
    else
      sql_query = "select * from rooms where "
      i = 1
      #Formation of SQL Query to show matching users to the search criteria.
      search_room.each do |key, value|
        sql_query = sql_query + "lower(#{key}) LIKE lower('%#{value}%')"
        if(i < search_room.length)
          sql_query = sql_query + " AND "
          i += 1
        end
      end
      @bookings = Booking.all
      @rooms = Room.find_by_sql(sql_query)
    end
    return @rooms,@bookings
  end
  def index
    @bookings = Booking.all
    @rooms=Room.all
    return @rooms,@bookings
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show

  end
def new_reservation
  @booking = Booking.new
  @room = Room.where("roomno LIKE ?", params[:roomno])

 ## @room = Room.find_by(roomno: params[:roomno])
  #render plain: @room.inspect
  #if @room.nil?
  #  flash[:notice] = "Room not found !"
   # render '/bookings/index'
  #end
  return @booking,@room
end
  # GET /bookings/new
  def new
    @booking = Booking.new
    @room = Room.find_by(roomno: params[:roomno])
    if @room.nil?
      flash[:notice] = "Room not found !"
      render '/bookings/index'
    end
    return @booking,@room
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create

    @booking = Booking.new(booking_params)
    @room = Room.where("roomno = ?", @booking.roomno)
    if @room.nil? or @room.empty?
      flash[:notice] = "Room not found !"
      render 'bookings/new' and return
    end
    if current_user.usertype != "Admin" and current_user.usertype != 'Super Admin'
      @user = User.where("email LIKE ?", @booking.booked_user)
    else
      @user = User.where("email LIKE ?", @booking.booked_user)
      if @user.nil? or @user.empty?
        flash[:notice] = "User not found !"
        render 'bookings/new' and return
      end
    end
    if @booking.starttime.past?
      flash[:notice] = "You cannot book for the day before today !"
      render 'bookings/new' and return
    end
    if (@booking.starttime-7.days).future?
      flash[:notice] = "You cannot book for a day i.e 7 days after today !"
      render 'bookings/new' and return
    end
    @current_bookings = Booking.where("roomno LIKE ? and ? <= endtime and starttime <= ? ", @booking.roomno,
                                              @booking.starttime, @booking.endtime)
    if not @current_bookings.nil? and not @current_bookings.empty?
      puts @current_bookings.first.starttime
      puts @current_bookings.first.roomno
      flash[:notice] = "This room is not available at this time. There is another booking which starts at #{@current_bookings.first.starttime} "
      render 'bookings/new' and return
    end
    if @booking.starttime > @booking.endtime
      flash[:notice] = "Booking start time can't be greater than end time"
      render 'bookings/new' and return
    end

    if @booking.starttime + 2.hours < @booking.endtime
      flash[:notice] = "Booking can be made only for 2 hours at a time"
      render 'bookings/new' and return
    end
    @booking.room_id = @room.first.id
    @booking.user_id = @user.first.id
    flash[:notice] = "#{@booking.user_id}"
    @newroom = Room.find(@booking.room_id)
    BookingMailer.booking_email(@booking.starttime,@booking.endtime,@booking.booked_user,@booking.roomno,@newroom.building).deliver_now!
    emails=params[:emails]
    values=emails.split(",")
    values.each do |value|
      BookingMailer.booking_email(@booking.starttime,@booking.endtime,value,@booking.roomno,@newroom.building).deliver_now!
    end
    respond_to do |format|

      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update

    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:roomno, :booked_user, :starttime, :endtime)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def options_for_time_select
    hour = Array.new
    for $h in 8..21 do
      for $m in ['00','30'] do
        hour.push [$h.to_s + "h" + $m.to_s, "%02d" % $h + ":" + $m + ":00"]
      end
    end
    hour
    end
end

app/views/bookings/_form.html.erb
<%= form_for @booking do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Room No" %>
    <%= f.number_field :roomno %>
  </div>
<% if current_user.usertype=='Super Admin' or current_user.usertype=='Admin' %>
  <div class="field">
    <%= f.label :booked_user %>
    <%= f.text_field :booked_user %>
  </div>
    <% else %>
    <%= f.hidden_field :booked_user, :value => current_user.email %>
    <% end %>
    <div class="field">
      <%= f.label :starttime %><br>
      <%= f.datetime_select :starttime, start_year: Date.today.year, end_year: Date.today.year+1, :minute_step => 30  %>
    </div>
    <div class="field">
      <%= f.label :endtime %><br>
      <%= f.datetime_select :endtime, start_year: Date.today.year, end_year: Date.today.year+1, :minute_step => 30 %>
    </div>
    Invite: <%= text_field_tag "emails" %> (please give emails in comma seperated eg: abc@gmail.com,xyz@gmail.com) <br><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<html>
<head>
  <title> List of Rooms </title>
  <style>
    body{
      background-color: #C0C0C0;
    }
  </style>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
    $( function() {
      $( "#datepicker" ).datepicker();
    } );
  </script>
</head>
<body>

<h3> Search By </h3>

<%= form_for :room, url: search_bookings_path, method: :get do |f| %>
    <div class="field">
      <%= f.label :"Room No" %><br>
      <%= f.text_field :roomno %>
    </div>
    <div class="field">
      <%= f.label :"Building" %><br>
      <%= f.select :building, ['','D.H.Hill', 'James.B.Hunt'] %>
    </div>
    <div class="field">
      <%= f.label :"Size" %><br>
      <%= f.select :size, ['' ,4,6,12] %>
    </div>

    <%= f.submit :Search %>
<% end %>
<h3> List of Reservations</h3>

<table border="1">
  <thead>
  <tr>
    <th>Room No</th>
    <th>Building</th>
    <th>Size</th>
    <th>start Time</th>
    <th>End Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>

      <% @bookings.each do |booking| %>
          <% if booking.starttime.future? or booking.endtime.future?%>

          <tr>
            <td><%= booking.roomno %></td>
            <% @rooms.each do |room| %>
                <% if room.roomno==booking.roomno %>
                    <td><%= room.building %></td>
                    <td><%= room.size %></td>
                <% end %>
            <% end %>
            <td><%= booking.starttime %></td>
            <td><%= booking.endtime %></td>
            <% if current_user.usertype=='Super Admin' or current_user.usertype=='Admin' or current_user.email==booking.booked_user %>
                <td> <%= button_to 'Release Room', booking, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %></td>
            <% end %>
            <td> <%= link_to 'Create Reservation', {:controller => "bookings", :action => "new_reservation", :roomno => booking.roomno} %></td>
        <%end%>
          <% end %>
  </tr>
  </tbody>
</table>
<h3> List of Rooms </h3>

<table border="1">
  <thead>
  <tr>
    <th>Room No</th>
    <th>Building</th>
    <th>Size</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @rooms.each do |room| %>
      <tr>
        <td><%= room.roomno %></td>
        <td><%= room.building %></td>
        <td><%= room.size %></td>
        <td> <%= link_to 'Create Reservation', {:controller => "bookings", :action => "new_reservation", :roomno => room.roomno} %></td>
  <% end %>
  </tr>
  </tbody>
</table>

</body>

app/views/bookings/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/new_reservation.html.erb
<h2>New Reservation</h2>
<%= form_for @booking do |f| %>
    <% if @booking.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

          <ul>
            <% @booking.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :"Room No" %>
      <%= f.number_field :roomno, :value=>params[:roomno] %>
    </div>
    <% if current_user.usertype=='Super Admin' or current_user.usertype=='Admin' %>
        <div class="field">
          <%= f.label :booked_user %>
          <%= f.text_field :booked_user %>
        </div>
    <% else %>
        <%= f.hidden_field :booked_user, :value => current_user.email %>
    <% end %>
    <div class="field">
      <%= f.label :starttime %><br>
      <%= f.datetime_select :starttime, start_year: Date.today.year, end_year: Date.today.year+1,:minute_step => 30 %>
    </div>
    <div class="field">
      <%= f.label :endtime %><br>
      <%= f.datetime_select :endtime, start_year: Date.today.year, end_year: Date.today.year+1,:minute_step => 30 %>
    </div>
    Invite: <%= text_field_tag "emails" %> (please give emails in comma seperated eg: abc@gmail.com,xyz@gmail.com) <br><br>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/bookings/search.html.erb
<html>
<head>
  <title> List of Rooms </title>
  <style>
    body{
      background-color: #C0C0C0;
    }
  </style>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
    $( function() {
      $( "#datepicker" ).datepicker();
    } );
  </script>
</head>
<body>

<h3> Search By </h3>

<%= form_for :room, url: search_bookings_path, method: :get do |f| %>
    <div class="field">
      <%= f.label :"Room No" %><br>
      <%= f.text_field :roomno %>
    </div>
    <div class="field">
      <%= f.label :"Building" %><br>
      <%= f.select :building, ['','D.H.Hill', 'James.B.Hunt'] %>
    </div>
    <div class="field">
      <%= f.label :"Size" %><br>
      <%= f.select :size, ['' ,4,6,12] %>
    </div>

    <%= f.submit :Search %>
<% end %>
<h3> List of Reservations </h3>

<table border="1">
  <thead>
  <tr>
    <th>Room No</th>
    <th>Building</th>
    <th>Size</th>
    <th>start Time</th>
    <th>End Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% if @bookings.nil? %>
      <% @rooms.each do |room| %>
          <tr>
            <td><%= room.roomno %></td>
            <td><%= room.building %></td>
            <td><%= room.size %></td>
            <td> No reservations </td>
            <td> No reservations </td>
            <td> <%= link_to 'Create Reservation', {:controller => "bookings", :action => "new_reservation", :roomno => room.roomno} %></td>

      <% end %>
      </tr>
  <% else %>
  <% @bookings.each do |booking| %>
      <tr>
        <% @rooms.each do |room| %>
            <% if room.roomno==booking.roomno and (booking.starttime.future? or booking.endtime.future? ) %>
                <td><%= booking.roomno %></td>
                <td><%= room.building %></td>
                <td><%= room.size %></td>
                <td><%= booking.starttime %></td>
                <td><%= booking.endtime %></td>
        <% if current_user.usertype=='Super Admin' or current_user.usertype=='Admin' or current_user.email==booking.booked_user %>
        <td> <%= button_to 'Release Room', booking,method: :delete,  confirm: 'Are you sure you want to delete it?'  %></td>
        <% end %>
        <td> <%= link_to 'Create Reservation', {:controller => "bookings", :action => "new_reservation", :roomno => booking.roomno} %></td>
            <% end %>
        <% end %>
            <% end %>
<% end %>
  </tr>
  </tbody>
</table>
<h3> List of Rooms </h3>

<table border="1">
  <thead>
  <tr>
    <th>Room No</th>
    <th>Building</th>
    <th>Size</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
        <% @rooms.each do |room| %>
      <tr>
                <td><%= room.roomno %></td>
                <td><%= room.building %></td>
                <td><%= room.size %></td>
                <td> <%= link_to 'Create Reservation', {:controller => "bookings", :action => "new_reservation", :roomno => room.roomno} %></td>
            <% end %>
  </tr>
  </tbody>
</table>
</body>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roomno:</strong>
  <%= @booking.roomno %>
</p>

<p>
  <strong>Booked user:</strong>
  <%= @booking.booked_user %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @booking.starttime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @booking.endtime %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>