config/routes.rb
Rails.application.routes.draw do
  resources :bookings do
    collection do
      get :search
      get :new_reservation

    end
  end
  resources :rooms do
    collection do
      get :search
      get :view_reservation
    end
  end

  resources :users do
    collection do
      post :login
      get :new_user
      get :logout
      get :search
      get :view_reservation
    end
  end

  root 'users#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length:{maximum:20}
  validates :password, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,length:{maximum:255},format: {with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_many :bookings, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :is_logged_in, only: [:new, :create, :login, :main]
  before_action :admin_logged_in, only: [:index, :new_user]
  # GET /users
  # GET /users.json
  def new_user
    @user = User.new
  end
  def index
    @users = User.all
  end
  def login
    @user = User.find_by(email: params[:user][:email])
    if @user && (@user.password == params[:user][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:notice] = "Invalid credentials"
      redirect_to '/'
    end
  end
  def logout
    session[:user_id] = nil
    redirect_to '/'
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end
  def search
    search_user = params[:user].reject {|key, value| value.empty? }
    if search_user.values.empty?
      sql_query = "select * from users"
      @users = User.find_by_sql(sql_query)
      return @users
    else
      sql_query = "select * from users where "
      i = 1
      #Formation of SQL Query to show matching users to the search criteria.
      search_user.each do |key, value|
        sql_query = sql_query + "lower(#{key}) LIKE lower('%#{value}%')"
        if(i < search_user.length)
          sql_query = sql_query + " AND "
          i += 1
        end
      end
      @users = User.find_by_sql(sql_query)
    end
  end
  def view_reservation
    @users=User.find_by(email: params[:email])
    @bookings=Booking.where(booked_user: params[:email])
    return @bookings,@users
  end
  # GET /users/1/edit
  def edit
    unless params[:id].to_i == current_user.id or current_user.usertype == 'Admin' or current_user.usertype == 'Super Admin'
      flash[:notice] = "You do not have permission to access these details."
      redirect_to '/'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      if @user.usertype == 'Member'
        redirect_to '/', notice: 'User was successfully created. Login to access home page.'
      else
        redirect_to '/', notice: 'User was successfully created.'
      end
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :password, :usertype)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :"Type of User" %>
    <%= f.select :usertype, ['Member', 'Admin'] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<html>
<head>
  <title> NCSU Library Room Booking </title>
  <style>
    body{
      background-color: #C0C0C0;
    }
  </style>
</head>
<body>
<h1>Editing User</h1>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% if @user.id == current_user.id %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email %>
        </div>
            <div class="field">
              <%= f.label :password %><br>
              <%= f.password_field :password %>
            </div>
            <div class="field">
              <%= f.hidden_field :usertype, :value => @user.usertype %>
            </div>
        <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', :back %>
</body>

app/views/users/index.html.erb
<ul>
  <li><%= link_to "Add Admin", new_user_users_path %></li>
</ul>

<%= form_for :user, url: search_users_path, method: :get do |f| %>
    <div class="field">
      <%= f.label :"Name" %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :"Email" %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :"User Type" %><br>
      <%= f.text_field :usertype %>
    </div>
    <%= f.submit :Search %>
<% end %>
<h3> List of Users </h3>

<table border="1">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>User Type</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.usertype %></td>
        <% if current_user.usertype == 'Super Admin' or current_user.usertype=='Admin'  %>
      <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'View Booking History', {:controller => "users", :action => "view_reservation", :email => user.email}  %></td>
        <% end %>
            <% if current_user.usertype == 'Super Admin' or current_user.usertype=='Admin' and current_user.email!=user.email and user.usertype!='Super Admin' %>
      <td><%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %></td>
        <% end %>
  <% end %>
  </tr>
  </tbody>
</table>

</body>

app/views/users/main.html.erb
<html>
<head>
  <title> NCSU Class Management System </title>
  <style>
    body{
      background-color: #C0C0C0;
    }
  </style>
</head>

app/views/users/new.html.erb
<html>
<head>
  <title> Member Registration | Library Room Booking </title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    body{
      background-color: #C0C0C0;
    }
  </style>
</head>
<body>
<h1>Registation form for New Members</h1>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <%= f.hidden_field :usertype, :value => 'Member' %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', '/' %>

</body>
</html>

app/views/users/new_user.html.erb
<html>
<head>
    <title> Create Admin </title>
    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <style>
        body{
            background-color: #C0C0C0;
        }
    </style>
</head>
<body>
<h1>New User</h1>

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
</div>
<div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
</div>
<div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
</div>
<div class="field">
    <%= f.label :"Type of User" %><br>
    <%= f.select :usertype, ['Admin','Member'] %>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

<%= link_to 'Back', '/' %>
</body>
</html>

app/views/users/search.html.erb
<ul>
  <li><%= link_to "Add Admin", new_user_users_path %></li>
</ul>

<%= form_for :user, url: search_users_path, method: :get do |f| %>
    <div class="field">
      <%= f.label :"Name" %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :"Email" %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :"User Type" %><br>
      <%= f.text_field :usertype %>
    </div>
    <%= f.submit :Search %>
<% end %>
<h3> List of Users </h3>

<table border="1">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>User Type</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.usertype %></td>
        <% if current_user.usertype == 'Super Admin' or current_user.usertype=='Admin'  %>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'View Booking History', {:controller => "users", :action => "view_reservation", :email => user.email}  %></td>
        <% end %>
        <% if current_user.usertype == 'Super Admin' or current_user.usertype=='Admin' and current_user.email!=user.email and user.usertype!='Super Admin' %>
            <td><%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %></td>
        <% end %>
  <% end %>
  </tr>
  </tbody>
</table>

</body>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<style>
  body{
    background-color: #C0C0C0;
  }
</style>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>



<p>
  <strong>Type:</strong>
  <%= @user.usertype %>
</p>
<% if @user.id == current_user.id %>
<%= link_to 'Edit', edit_user_path(@user) %>
    <% end %>
<%= link_to 'Back', users_path %>

app/views/users/view_reservation.html.erb
<p id="notice"><%= notice %></p>
<style>
  body{
    background-color: #C0C0C0;
  }
</style>
<h1><%= @users.name %> | Reservations </h1>
<% if current_user.email==@users.email or current_user.usertype=='Super Admin' or current_user.usertype=='Admin' %>
<table border="1">
  <thead>
  <tr>
    <th>Room no</th>
    <th>Building</th>
    <th>Size</th>
    <th>Start Time</th>
    <th>End Time</th>
  </tr>
  </thead>
  <tbody>
<% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.roomno %></td>
        <% @room=Room.find_by(roomno:  booking.roomno) %>
        <td><%= @room.building %></td>
        <td><%= @room.size %></td>
        <td><%= booking.starttime %></td>
        <td><%= booking.endtime %></td>
  <% end %>
  </tr>
  </tbody>
</table>
<% else %>
    <h3> Sorry you cannot view these details</h3>
    <% end %>

<%= link_to 'Back', users_path %>