config/routes.rb
Rails.application.routes.draw do
  resources :bookings do
    collection do
      get :search
      get :new_reservation

    end
  end
  resources :rooms do
    collection do
      get :search
      get :view_reservation
    end
  end

  resources :users do
    collection do
      post :login
      get :new_user
      get :logout
      get :search
      get :view_reservation
    end
  end

  root 'users#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  validates :roomno, :presence => true, :uniqueness => true
  validates :size, :presence => true
  validates :building,  :presence => true
  has_many :bookings, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end
  def search
    search_room = params[:room].reject {|key, value| value.empty? }
    if search_room.values.empty?
      sql_query = "select * from rooms"
      @rooms = Room.find_by_sql(sql_query)
      return @rooms
    else
      sql_query = "select * from rooms where "
      i = 1
      #Formation of SQL Query to show matching users to the search criteria.
      search_room.each do |key, value|
        sql_query = sql_query + "lower(#{key}) LIKE lower('%#{value}%')"
        if(i < search_room.length)
          sql_query = sql_query + " AND "
          i += 1
        end
      end
      @rooms = Room.find_by_sql(sql_query)
    end
  end
  def view_reservation
    @bookings=Booking.where(roomno: params[:roomno])
    #render plain @bookings.inspect
    return @bookings
  end
  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:roomno, :building, :size, :status)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :roomno %>
    <%= f.number_field :roomno %>
  </div>

  <div class="field">
    <%= f.label :building %>
    <%= f.select :building, ['','D.H.Hill', 'James.B.Hunt'] %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.select :size, ['',4,6,12] %>
  </div>

      </div>
      <%= f.hidden_field :status, :value => 'Available' %>
      </div>
  <div class="actions">
    <%= f.submit %>
  </div>
        <% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<ul>
  <% if current_user.usertype == 'Super Admin' or current_user.usertype=='Admin'  %>
<li><%= link_to "Add Rooms", new_room_path %></li>
  <% end %>
<li><%= link_to "Book a Room", bookings_path %></li>
</ul>

<%= form_for :room, url: search_rooms_path, method: :get do |f| %>
    <div class="field">
      <%= f.label :"Room No" %><br>
      <%= f.text_field :roomno %>
    </div>
    <div class="field">
      <%= f.label :"Building" %><br>
      <%= f.select :building, ['','D.H.Hill', 'James.B.Hunt'] %>
    </div>
    <div class="field">
      <%= f.label :"Size" %><br>
      <%= f.select :size, ['',4,6,12] %>
    </div>
    <%= f.submit :Search %>
<% end %>
<h3> List of Rooms </h3>

<table border="1">
  <thead>
  <tr>
    <th>Room No</th>
    <th>Building</th>
    <th>Size</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @rooms.each do |room| %>
      <tr>
        <td><%= room.roomno %></td>
        <td><%= room.building %></td>
        <td><%= room.size %></td>
        <td><%= link_to 'Show', room %></td>
        <% if current_user.usertype == 'Super Admin' or current_user.usertype=='Admin'  %>
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <td><%= link_to 'View Booking History', {:controller => "rooms", :action => "view_reservation", :roomno => room.roomno}  %></td>
            <td><%= button_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %></td>

        <% end %>
  <% end %>
  </tr>
  </tbody>
</table>

</body>

app/views/rooms/main.html.erb
<html>
<head>
  <title> NCSU Class Management System </title>
  <style>
    body{
      background-color: #C0C0C0;
    }
  </style>
</head>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/search.html.erb
<ul>
  <% if current_user.usertype == 'Super Admin' or current_user.usertype=='Admin'  %>
      <li><%= link_to "Add Rooms", new_room_path %></li>
  <% end %>
  <li><%= link_to "Book a Room", bookings_path %></li>
</ul>
<html>
<head>
  <title> List of Rooms </title>
  <style>
    body{
      background-color: #C0C0C0;
    }
  </style>
</head>
<body>

<h3> List of Rooms </h3>

<%= form_for :room, url: search_rooms_path, method: :get do |f| %>
    <div class="field">
      <%= f.label :"Room No" %><br>
      <%= f.text_field :roomno %>
    </div>
    <div class="field">
      <%= f.label :"Building" %><br>
      <%= f.select :building, ['','D.H.Hill', 'James.B.Hunt'] %>
    </div>
    <div class="field">
      <%= f.label :"Size" %><br>
      <%= f.select :size, ['',4,6,12] %>
    </div>
    <%= f.submit :Search %>
<% end %>

<table border="1" width="500px">
  <thead>
  <tr>
    <th>Room No</th>
    <th>Building</th>
    <th>Size</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
      <tr>
        <td><%= room.roomno %></td>
        <td><%= room.building %></td>
        <td><%= room.size %></td>
        <td><%= link_to 'Show', room %></td>
        <% if current_user.usertype == 'Super Admin' or current_user.usertype=='Admin'  %>
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <td><%= link_to 'View Booking History', {:controller => "rooms", :action => "view_reservation", :roomno => room.roomno}  %></td>
            <td><%= button_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %></td>

        <% end %>
  <% end %>
  </tr>
  </tbody>
</table>

</body>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roomno:</strong>
  <%= @room.roomno %>
</p>

<p>
  <strong>Building:</strong>
  <%= @room.building %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>
<% if current_user.usertype=='Super Admin' or current_user.usertype=='Admin' %>
<%= link_to 'Edit', edit_room_path(@room) %>
    <% end %>
<%= link_to 'Back', rooms_path %>

app/views/rooms/view_reservation.html.erb
<p id="notice"><%= notice %></p>
<style>
  body{
    background-color: #C0C0C0;
  }
</style>
<table border="1">
  <thead>
  <tr>
    <th>Booked User</th>
    <th>Building</th>
    <th>Size</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th colspan="4"></th>
  </tr>
  </thead>
  <tbody>
  <% i=1 %>
  <% @bookings.each do |booking| %>
      <tr>
       <% if i==1 %>
            <h1><%= booking.roomno %> | Reservations </h1>
            <% i=i+1 %>
        <% end %>
            <% @users=User.find_by(email:  booking.booked_user) %>
        <% @rooms=Room.find_by(roomno:  booking.roomno) %>
        <td><%= @users.name %></td>
        <td><%= @rooms.building %></td>
        <td><%= @rooms.size %></td>
        <td><%= booking.starttime %></td>
        <td><%= booking.starttime+2.hours %></td>
  <% end %>
  </tr>
  </tbody>
</table>


<%= link_to 'Back', rooms_path %>